// Code generated by sqlc. DO NOT EDIT.
// source: role.sql

package db

import (
	"context"
)

const selectRoleByCode = `-- name: SelectRoleByCode :one
SELECT id, code, name FROM "role"
WHERE code = $1
`

func (q *Queries) SelectRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRowContext(ctx, selectRoleByCode, code)
	var i Role
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}
